import type { NextPage } from "next";
import React from "react";
import { GetStaticProps } from "next";
import Head from "next/head";
import axios from "axios";
import AboutN from "../../components/navbar/aboutN";
import LetsWork from "../../components/Homepage/Others/letsWork";
import Footer from "../../components/Footer/Footer";
import Spost from "../../components/Blogs/Post/singlePost";
import styled from "styled-components";
import Form from "../../components/Blogs/FormSingle/Form";

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const { data } = await axios.get(
    `https://iwebcodestrapi.herokuapp.com/posts/${params?.id}`
  );
  return {
    props: {
      data,
    },
  };
};

export const getStaticPaths = async () => {
  return {
    paths: [
      "/blog/1",
      "/blog/2",
      "/blog/3",
      "/blog/4",
      "/blog/5",
      "/blog/6",
      "/blog/7",
      "/blog/8",
      "/blog/9",
    ],
    fallback: false,
  };
};

const Post = styled.div``;

const Center = styled.div`
  min-height: 230px;
  max-width: 1170px;
  .heading {
    font-size: 55px;
    line-height: 227px;
    letter-spacing: 1px;
    font-weight: bolder;
    padding-left: 13px;
  }
  ul {
    padding: 0;
    li {
      font-size: 15px;
      line-height: 24px;
      font-weight: 400;
      color: #757589;
      margin: 0;
      cursor: pointer;
      margin-left: 1.5rem;
      &:hover {
        color: #844ff7;
      }
    }
  }
  @media (max-width: 968px) {
    .height {
      height: 215px !important;
    }
    padding: 0 20px;
  }
`;

const Blog: NextPage = (props: any) => {
  return (
    <section className="" style={{ background: "#F7F7FF" }}>
      <Head>
        <title>Blog Posts - IWEBCODE</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossOrigin="anonymous"
        />
        <script
          defer
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
          crossOrigin="anonymous"
        ></script>
      </Head>

      <AboutN />
      <section>
        <Center className="container-fluid">
          <div className="row w-100 g-0">
            <p className="col height d-flex align-items-center g-0">
              <ul className="d-flex flex-wrap w-100">
                <li className="mr-3 list-unstyled px-0 mx-0">Home</li>
                <li className="mr-3">Uncategorized</li>
                <li className="mr-3">Why Off Page Optimization is i ...</li>
              </ul>
            </p>
            <div className="col d-lg-flex d-none heading align-items-center justify-content-center">
              svg
            </div>
          </div>
        </Center>
      </section>
      <Post className="container-fluid g-0">
        <Spost post={props} />
      </Post>
      <Form />

      <LetsWork />
      <Footer />
    </section>
  );
};

export default Blog;
