import type { NextPage } from "next";
import React from "react";
import Head from "next/head";

import AboutN from "../components/navbar/aboutN";
import LetsWork from "../components/Homepage/Others/letsWork";
import Footer from "../components/Footer/Footer";

import Main from "../components/Blogs/Main/main";
import Posts from "../components/Blogs/Posts/Posts";

import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import Link from "next/link";
import styled from "styled-components";
import { FaArrowLeft, FaArrowRight } from "react-icons/fa";

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://iwebcodestrapi.herokuapp.com/graphql",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query {
        posts {
          id
          publishedDate
          Description
          Heading
          Tags
          Thumbnail {
            url
          }
        }
      }
    `,
  });

  return {
    props: {
      post: data,
    },
  };
}

const Pages = styled.div`
  background: #fff;
  .row {
    max-width: 1170px !important;
  }
  button {
    line-height: 42px;
    min-width: 42px;
    text-align: center;
    color: #000248;
    margin-right: 10px;
    padding: 0 15px;
    background: none;
    border: 1px solid #d3d3d3;
    &:hover {
      color: white;
      background: #844ff7;
    }
  }
`;

const Blogs: NextPage = (props: any) => {
  console.log(props.post.posts);
  return (
    <section className="" style={{ background: "#F7F7FF" }}>
      <Head>
        <title>Blog Posts - IWEBCODE</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossOrigin="anonymous"
        />
        <script
          defer
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
          crossOrigin="anonymous"
        ></script>
      </Head>

      <AboutN />
      <Main />
      <Posts Post={props.post} />

      <Pages className="py-5 pt-2 container-fluid d-flex justify-content-center aling-items-center">
        <div className="row mb-5 g-0 w-100">
          <div className="col">
            <Link href="/blogs" passHref>
              <button className="">1</button>
            </Link>
            <Link href="/blogs" passHref>
              <button className="">2</button>
            </Link>
            <Link href="/blogs" passHref>
              <button className="">3</button>
            </Link>
            <Link href="/blogs" passHref>
              <button className="">4</button>
            </Link>
            <Link href="/blogs" passHref>
              <button className="">5</button>
            </Link>
            <Link href="/blogs" passHref>
              <button className="">
                <FaArrowRight />
              </button>
            </Link>
          </div>
        </div>
      </Pages>
      <LetsWork />
      <Footer />
    </section>
  );
};

export default Blogs;
