import type { NextPage } from "next";
import React from "react";
import Head from "next/head";

import AboutN from "../components/navbar/aboutN";
import LetsWork from "../components/Homepage/Others/letsWork";
import Footer from "../components/Footer/Footer";

import Main from '../components/Blogs/Main/main'
import Posts from "../components/Blogs/Posts/Posts";

import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://iwebcodestrapi.herokuapp.com/posts',
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query {
        posts {
          id
          publishedDate
          Description
          Heading
          Tags
          Thumbnail {
            url
          }
        }
      }
    `,
  });

  return {
    props: {
      post: data,
    },
  };
}


const Blogs:NextPage = (props: any) => {
  console.log( props );
  return (
    <section className="" style={{ background: "#F7F7FF" }}>
      <Head>
        <title>Blog Posts - IWEBCODE</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossOrigin="anonymous"
        />
        <script
          defer
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
          crossOrigin="anonymous"
        ></script>
      </Head>

      <AboutN />
      <Main />
      <Posts Post={props.post}/>
      <LetsWork />
      <Footer />

    </section>
  );
};

export default Blogs;
