import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/header/header";
import Navbar from "../components/navbar/navbar";
import Services from "../components/services/services";
import Cases from "../components/CaseStudies/cases"
import styles from "../styles/Home.module.css";
import About from "../components/AboutPage/about";
import Projects from "../components/Projects/projects";
import Testimonial from "../components/Others/testimonial";
import Clients from "../components/Others/clients";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossOrigin="anonymous"
        />
        <script
          defer
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <Header />
      <Services />
      <Cases />
      <About />
      <Projects />
      <Testimonial />
      <Clients />
    </div>
  );
};

export default Home;
